# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bbb2d48839d2d3bb9222879056607694aa426917e2a728faf729ca90878ddab30c3a5eb1e6e3301b555a0087573294ad73599a8433d0acb95962a86d1a7257

test:
  secret_key_base: 186854b1154bfa38c9c5d9a138d5d5d30d553024bff5b550970cdcfef5d1f57c4b0f659aa55a94060fca4e030ace7e13550f3bbb26ed2d79c130d4a349fc3c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
